### ISSUE TITLE
crash when teleporting

### ISSUE THREAD

**Issue by SilverBackSpartan** [TheUnderTaker11/Staff-Of-Traveling-Keybind#1]
[crash-2021-11-11_14.27.34-client.txt](https://github.com/TheUnderTaker11/Staff-Of-Traveling-Keybind/files/7522827/crash-2021-11-11_14.27.34-client.txt)

**Comment by TheUnderTaker11** [comment]
I had accidently archived v1.4 for 1.12.2 when uploading 1.7.10's port. Download latest version.

**Comment by SilverBackSpartan** [comment]
will test
